const fs = require("fs");
const path = require("path");
const { ethers, network, artifacts } = require("hardhat");

const FRONTEND_LIB = path.join(__dirname, "..", "..", "frontend", "src", "lib");

/// Writes the ABI into the frontend as a typed `as const` array so viem can
/// infer argument and return types from it. Run automatically after deploy.
async function exportAbi() {
  const artifact = await artifacts.readArtifact("MachineWalletManager");
  if (!fs.existsSync(FRONTEND_LIB)) fs.mkdirSync(FRONTEND_LIB, { recursive: true });

  const out = `// Generated by contracts/scripts/exportAbi.js — do not edit by hand.
export const machineWalletManagerAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  fs.writeFileSync(path.join(FRONTEND_LIB, "abi.ts"), out);
  console.log(`ABI written to frontend/src/lib/abi.ts (${artifact.abi.length} entries)`);
}

/// Records the address per chain id so the frontend needs no manual config
/// after a deploy. Safe to commit — addresses only, no keys.
function recordDeployment(chainId, address, deployer, blockNumber) {
  const file = path.join(FRONTEND_LIB, "deployments.json");
  const existing = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : {};
  existing[String(chainId)] = {
    address,
    deployer,
    network: network.name,
    // Log queries start here instead of at genesis, which public RPCs refuse.
    blockNumber: blockNumber !== undefined ? Number(blockNumber) : undefined,
    deployedAt: new Date().toISOString(),
  };
  fs.writeFileSync(file, `${JSON.stringify(existing, null, 2)}\n`);
  console.log("Deployment recorded in frontend/src/lib/deployments.json");
}

module.exports = { exportAbi, recordDeployment, FRONTEND_LIB };

if (require.main === module) {
  exportAbi().catch((e) => {
    console.error(e);
    process.exitCode = 1;
  });
}
