// Generated by contracts/scripts/exportAbi.js — do not edit by hand.
export const machineWalletManagerAbi = [
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "fromId",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "toId",
        "type": "string"
      }
    ],
    "name": "CounterpartyNotAllowed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "requested",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "remainingToday",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "dailyLimit",
        "type": "uint256"
      }
    ],
    "name": "DailyLimitExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyMachineId",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "requested",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "available",
        "type": "uint256"
      }
    ],
    "name": "InsufficientBalance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "MachineAlreadyExists",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "MachineIsPaused",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "MachineNotFound",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "caller",
        "type": "address"
      }
    ],
    "name": "NotAuthorized",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "caller",
        "type": "address"
      }
    ],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "SelfPayment",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "requested",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "limit",
        "type": "uint256"
      }
    ],
    "name": "SpendingLimitExceeded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TransferFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAmount",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "enabled",
        "type": "bool"
      }
    ],
    "name": "AllowlistEnabledChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "previousController",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "newController",
        "type": "address"
      }
    ],
    "name": "ControllerUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "counterpartyId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "allowed",
        "type": "bool"
      }
    ],
    "name": "CounterpartyUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "previousLimit",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newLimit",
        "type": "uint256"
      }
    ],
    "name": "DailyLimitUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newBalance",
        "type": "uint256"
      }
    ],
    "name": "Deposited",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineType",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "controller",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "spendingLimit",
        "type": "uint256"
      }
    ],
    "name": "MachineCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnershipTransferred",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "paused",
        "type": "bool"
      }
    ],
    "name": "PauseStateChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "fromKey",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "toKey",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "fromId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "toId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "initiator",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "paymentIndex",
        "type": "uint256"
      }
    ],
    "name": "PaymentExecuted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "previousLimit",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newLimit",
        "type": "uint256"
      }
    ],
    "name": "SpendingLimitUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Withdrawn",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "fromId",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "toId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "initiator",
        "type": "address"
      }
    ],
    "name": "canPay",
    "outputs": [
      {
        "internalType": "bool",
        "name": "allowed",
        "type": "bool"
      },
      {
        "internalType": "string",
        "name": "reason",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string[]",
        "name": "ids",
        "type": "string[]"
      }
    ],
    "name": "counterpartyMatrix",
    "outputs": [
      {
        "internalType": "bool[]",
        "name": "flags",
        "type": "bool[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "machineType",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "controller",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "spendingLimit",
        "type": "uint256"
      }
    ],
    "name": "createMachine",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "machineType",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "controller",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "spendingLimit",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "dailyLimit",
        "type": "uint256"
      },
      {
        "internalType": "string[]",
        "name": "allowedCounterparties",
        "type": "string[]"
      }
    ],
    "name": "createMachineWithPolicy",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "deposit",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getAllMachines",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "machineId",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "machineType",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "controller",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "balance",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spendingLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalSpent",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalReceived",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "allowlistEnabled",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "exists",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "dailyLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spentToday",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "dayIndex",
            "type": "uint256"
          }
        ],
        "internalType": "struct MachineWalletManager.Machine[]",
        "name": "list",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "getBalance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "getMachine",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "machineId",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "machineType",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "controller",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "balance",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spendingLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalSpent",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalReceived",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "allowlistEnabled",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "exists",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "dailyLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spentToday",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "dayIndex",
            "type": "uint256"
          }
        ],
        "internalType": "struct MachineWalletManager.Machine",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "key",
        "type": "bytes32"
      }
    ],
    "name": "getMachineByKey",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "machineId",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "machineType",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "controller",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "balance",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spendingLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalSpent",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalReceived",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "allowlistEnabled",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "exists",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "dailyLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spentToday",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "dayIndex",
            "type": "uint256"
          }
        ],
        "internalType": "struct MachineWalletManager.Machine",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string[]",
        "name": "ids",
        "type": "string[]"
      }
    ],
    "name": "getMachinesByIds",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "machineId",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "machineType",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "controller",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "balance",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spendingLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalSpent",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalReceived",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "allowlistEnabled",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "exists",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "dailyLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "spentToday",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "dayIndex",
            "type": "uint256"
          }
        ],
        "internalType": "struct MachineWalletManager.Machine[]",
        "name": "list",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      }
    ],
    "name": "getPayment",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "fromKey",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "toKey",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "initiator",
            "type": "address"
          }
        ],
        "internalType": "struct MachineWalletManager.Payment",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "limit",
        "type": "uint256"
      }
    ],
    "name": "getPayments",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "fromKey",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "toKey",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "initiator",
            "type": "address"
          }
        ],
        "internalType": "struct MachineWalletManager.Payment[]",
        "name": "page",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "count",
        "type": "uint256"
      }
    ],
    "name": "getRecentPayments",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "fromKey",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "toKey",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "initiator",
            "type": "address"
          }
        ],
        "internalType": "struct MachineWalletManager.Payment[]",
        "name": "page",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "getSpendingLimit",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "fromId",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "toId",
        "type": "string"
      }
    ],
    "name": "isCounterpartyAllowed",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "keyOf",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "machineCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "machineExists",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "pauseMachine",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "fromId",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "toId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "payMachine",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "paymentIndex",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "paymentCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "remainingToday",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "bool",
        "name": "enabled",
        "type": "bool"
      }
    ],
    "name": "setAllowlistEnabled",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "controller",
        "type": "address"
      }
    ],
    "name": "setController",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "counterpartyId",
        "type": "string"
      },
      {
        "internalType": "bool",
        "name": "allowed",
        "type": "bool"
      }
    ],
    "name": "setCounterpartyAllowed",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "newLimit",
        "type": "uint256"
      }
    ],
    "name": "setDailyLimit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "newLimit",
        "type": "uint256"
      }
    ],
    "name": "setSpendingLimit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalLedger",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferMachineOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "unallocatedBalance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      }
    ],
    "name": "unpauseMachine",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "machineId",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
